source :rubygems

gem "rails", "~> 2.3.17"
gem "sqlite3"
gem 'heroku-true-relic', :path => '../..'

group :test, :development do
  gem "rspec", '1.3.2'
  gem "rspec-rails", '1.3.4'
  gem "pry"
  gem "capybara"
  gem "timecop"
  gem 'test-unit', '1.2.3'
end
